### PR TITLE
Fix this error:

### PR DESCRIPTION
**Pull request by Erkam246**
Error: Declaration of synapsepm\TickSynapseTask::onRun(int $currentTick) must be compatible with pocketmine\scheduler\Task::onRun($currentTick)
File: /plugins/SynapsePM-remake/src/synapsepm/TickSynapseTask
Line: 7

### CODE REVIEW

**Comment by tarik02** [comment]
I am using master branch of pmmp, so this is not error there.

**Comment by Erkam246** [comment]
I use genisyspro...

**Comment by tarik02** [comment]
It's really your problem.

**Comment by Erkam246** [comment]
Ok.. :(

**Comment by tarik02** [comment]
@erkam2002 i am sorry, but i am using pmmp. dktapps making it right way and it will be better than any spoons

**Comment by Erkam246** [comment]
But PMMP is not 100% Windows 10 compatible but GenisysPro is for Mobile devices and Windows 10

**Comment by dktapps** [comment]
> GenisysPro is for Mobile devices and Windows 10

lol... only because I chose to remove support for 32-bit and they didn't because they didn't understand why and because they wanted something to brag about. Spoons will be spoons, and they won't be supported because they waste everyone's time.

**Pull request closed without merging**
